In [27]:
#Task condition 1.3.1
#Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

#solution
import numpy as np
a = np.zeros((8, 8), 'int')
for i in range(0, 8):
    for j in range(0, 8):
        if i % 2 == 0 and j % 2 == 0: a[i][j] = 1
        elif i % 2 == 1 and j % 2 == 1: a[i][j] = 1
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [28]:
#Task condition 1.3.2
#Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arange.

#solution
import numpy as np
a = np.zeros((5, 5), 'int')
for i in range (len(a)): a[i] = np.arange(5)
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [30]:
#Task condition 1.3.3
#Создать массив 3x3x3 со случайными значениями.

#solution
import numpy as np
print(np.random.random((3, 3, 3)))

[[[0.18987442 0.72778883 0.73895199]
  [0.17733312 0.0060583  0.90777067]
  [0.80316698 0.85199653 0.52909727]]

 [[0.44284681 0.52943288 0.65532028]
  [0.39357884 0.02523806 0.6453388 ]
  [0.03633548 0.40304286 0.96312154]]

 [[0.50007201 0.10172871 0.88787317]
  [0.13238299 0.21419686 0.70262965]
  [0.36037537 0.66583037 0.12597469]]]


In [1]:
#Task condition 1.3.4
#Создать матрицу с 0 внутри, и 1 на границах.

#solution
import numpy as np
a = np.zeros((int(input()), int(input())), 'int')
a[0] = np.ones(len(a[0]))
a[len(a) - 1] = np.ones(len(a[0]))
for i in range(len(a)):
    a[i][0] = 1
    a[i][len(a[i]) - 1] = 1
print(a)

10
10
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [15]:
#Task condition 1.3.5
#Создайте массив и отсортируйте его по убыванию.

#solution
import numpy as np
a = (np.random.random((int(input()))))
print(sorted(a, reverse=True))

5
[0.7792001380915395, 0.32863867296954397, 0.3037519259611956, 0.23135843351126995, 0.16104188685594234]


In [25]:
##### Task condition 1.3.6
#Создайте матрицу, выведите ее форму, размер и размерность.

#solution
import numpy as np
s = []
while True:
    i = input()
    if i != 'stop': s.append(int(i))
    else: break
a = np.sort(np.random.random((s)))
#форма
print(a.shape)
#размер
print(a.size)
#размерность
print(a.ndim)

2
2
2
2
stop
(2, 2, 2, 2)
16
4


In [27]:
# Task condition 2.3.1
#Найдите евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу.


#solution
import pandas as pd
import numpy as np
from termcolor import colored, cprint
print(colored('Введите координаты точек. Для перехода к следущей точке введите "next". Для завершения введите "stop"', 'red', attrs=['underline']))
coordinates = []
l = []
while True:
    i = input()
    if i == 'stop': 
        coordinates.append(l)
        break
    elif i == 'next': 
        coordinates.append(l)
        l = []
    else:
        l.append(int(i))
print(colored('Выберите порядковые номера двух точек, между которыми нужно посчитать евклидово расстояние: от 1 до ' + str(len(coordinates)) + '.', 'red', attrs=['underline']))
x = pd.Series(coordinates[int(input()) - 1])
y = pd.Series(coordinates[int(input()) - 1])
dist = np.sqrt(np.sum([(a - b)*(a - b) for a, b in zip(x, y)]))  
print(dist)


Введите координаты точек. Для перехода к следущей точке введите "next". Для завершения введите "stop"
1
0
0
next
0
1
0
stop
Выберите порядковые номера двух точек, между которыми нужно посчитать евклидово расстояние: от 1 до 2.
1
2
1.4142135623730951


In [8]:
#Task condition 2.3.2
#Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных.

#solution
import pandas as pd
data = pd.read_csv(r'C:\Users\Reens\Desktop\jupiter\bank_marketing.csv')
df = pd.DataFrame(data)
print(df)

       V1            V2        V3         V4  V5    V6   V7   V8         V9  \
0      58    management   married   tertiary  no  2143  yes   no    unknown   
1      44    technician    single  secondary  no    29  yes   no    unknown   
2      33  entrepreneur   married  secondary  no     2  yes  yes    unknown   
3      47   blue-collar   married    unknown  no  1506  yes   no    unknown   
4      33       unknown    single    unknown  no     1   no   no    unknown   
...    ..           ...       ...        ...  ..   ...  ...  ...        ...   
45206  51    technician   married   tertiary  no   825   no   no   cellular   
45207  71       retired  divorced    primary  no  1729   no   no   cellular   
45208  72       retired   married  secondary  no  5715   no   no   cellular   
45209  57   blue-collar   married  secondary  no   668   no   no  telephone   
45210  37  entrepreneur   married  secondary  no  2971   no   no   cellular   

       V10  V11   V12  V13  V14  V15      V16  Clas

In [23]:
#Task condition 2.3.2
#Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7.

#solution
import pandas as pd
data = pd.read_csv(r'C:\Users\Reens\Desktop\jupiter\bank_marketing.csv')
print(colored('Выберите порядковый номер строки, до которой хотите прочитать таблицу (включительно): от 1 до ' + str(len(data)) + '.', 'red', attrs=['underline']))
print(data.head(int(input())))
print(colored('Выберите порядковый номер строки, c которой хотите прочитать таблицу (включительно): от 1 до ' + str(len(data)) + '.', 'red', attrs=['underline']))
print(data.tail(len(data) - int(input())))
print(colored('Выберите порядковые номера строк, которые будут являться границами желаемого среза (включительно): от 1 до ' + str(len(data)) + '.', 'red', attrs=['underline']))
print(data.iloc[int(input()):int(input())], '\n')
print(data.shape)
print(data.describe())
print(data[data['V3'] == 'single'])

Выберите порядковый номер строки, до которой хотите прочитать таблицу (включительно): от 1 до 45211.
5
   V1            V2       V3         V4  V5    V6   V7   V8       V9  V10  \
0  58    management  married   tertiary  no  2143  yes   no  unknown    5   
1  44    technician   single  secondary  no    29  yes   no  unknown    5   
2  33  entrepreneur  married  secondary  no     2  yes  yes  unknown    5   
3  47   blue-collar  married    unknown  no  1506  yes   no  unknown    5   
4  33       unknown   single    unknown  no     1   no   no  unknown    5   

   V11  V12  V13  V14  V15      V16  Class  
0  may  261    1   -1    0  unknown      1  
1  may  151    1   -1    0  unknown      1  
2  may   76    1   -1    0  unknown      1  
3  may   92    1   -1    0  unknown      1  
4  may  198    1   -1    0  unknown      1  
Выберите порядковый номер строки, c которой хотите прочитать таблицу (включительно): от 1 до 45211.
45207
       V1            V2        V3         V4  V5    V6  V7

In [32]:
#Task condition 3.3.2
#Загрузить фрейм данных по ссылке: https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
#Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а второго (sepal_width_cm) с задействованием z-масштабирования.

#solution
import pandas as pd
import numpy as np
from sklearn import svm 
from sklearn import datasets
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
data = pd.read_csv(r'C:\Users\Reens\Desktop\jupiter\raw.githubusercontent.com_akmand_datasets_master_iris.csv')
scaler = preprocessing.MinMaxScaler()
data[['sepal_length_cm']] = scaler.fit_transform(data[['sepal_length_cm']])
scaler = StandardScaler()
data[['sepal_width_cm']] = scaler.fit_transform(data[['sepal_width_cm']])
print(data)

     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145 